name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: Tests PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.2]

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
          coverage: none

      - name: Copy .env.test
        run: php -r "file_exists('.env') || copy('.env.test', '.env');"

      - name: Install Composer dependencies
        run: |
          composer update --no-interaction --no-progress
          composer install --prefer-dist --no-progress

      - name: Create test database
        run: |
          mkdir -p var
          touch var/test.db

      - name: Run tests
        env:
          DATABASE_URL: "sqlite:///%kernel.project_dir%/var/test.db"
          APP_ENV: test
          KERNEL_CLASS: 'App\Kernel'
        run: |
          php bin/console doctrine:schema:create --env=test
          php bin/phpunit
